OUTPUT_DIR: ".../ARAI-RMVSNet/outputs/dtu/test"
DESCRIPTION: "N 7 D[16,64,16,8] H W 960 1280"
DATA:
  TEST:
    ROOT_DIR: ".../MVS_Testing/dtu"
    TEST_LIST: ".../ARAI-MVSNet/mvsnet/dataloader/datalist/dtu/test.txt"
    NUM_VIEW: 7
    IMG_HEIGHT: 960
    IMG_WIDTH: 1280
    INTER_SCALE: 2.13
MODEL:
  NET_CONFIGS: "16,64,16,8"
  LAMB: 1.5
  LOSS_WEIGHTS: "0.5,1.0,1.5,2.0"
SCHEDULER:
  TYPE: "StepLR"
  FLOW1_EPOCH: 0
  FLOW2_EPOCH: 0
  MAX_EPOCH: 16
  StepLR:
    gamma: 0.9
    step_size: 2
SOLVER:
  BASE_LR: 0.0006
  WEIGHT_DECAY: 0.001
  TYPE: 'RMSprop'
TRAIN:
  BATCH_SIZE: 1
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 10
  VAL_PERIOD: 1
TEST:
  WEIGHT: ""
  BATCH_SIZE: 1
  SAVE_PATH: ".../ARAI-RMVSNet/outputs/dtu/test/result"


